#-------------------------------------------------------------
# Configuration -- set up accordingly
#-------------------------------------------------------------

# Location of LLVM/MLIR, TensorFlow, IREE
# ATTENTION: iree and TF binaries are located in the bazel cache
LLVMDIR=$(HOME)/llvm
IREE_BIN_DIR=$(HOME)/.cache/bazel/_bazel_hpompougnac/c21dee9b578a4b1c3f60a275119db250/execroot/iree_core/bazel-out/k8-opt/bin
TF_BIN_DIR=$(HOME)/.cache/bazel/_bazel_hpompougnac/52c22a949d9769dd1d18ce3d575a5e05/execroot/org_tensorflow/bazel-out/k8-opt/bin

# Location of mlirlus and mlirprime
MLIRLUSDIR=../../../mlir-lus
MLIRPRIMEDIR=../../../mlir-prime

# Compiler setup
CC=clang -O3
# CC=clang
LD=clang
LDFLAGS=-lm
LLC = llc -O3 --fp-contract=fast 
# LLC = llc

#-------------------------------------------------------------
# DO NOT CHANGE
#-------------------------------------------------------------

MLIRLUS = $(MLIRLUSDIR)/mlirlus
LUSAUTO = "--normalize --to-sync-automata --sync-to-std"
MLIRPRIME = $(MLIRLUSDIR)/mlirprime
MLIROPT = $(LLVMDIR)/bin/mlir-opt
MLIRTRANS = $(LLVMDIR)/bin/mlir-translate
IREE_OPT=iree-opt
TF_OPT=tf-opt

