#-------------------------------------------------------------
# Configuration -- set up accordingly
#-------------------------------------------------------------

# IREE_DIR=/local/hpompoug/github/iree
IREE_DIR=~/Documents/src/iree/
IREE_BUILD_DIR=~/Documents/src/iree-build/
# IREE_BUILD_DIR=/local/hpompoug/bin/iree-build
TF_OPT=tf-opt
IREE_OPT=iree-opt
IREE_TRANSLATE=iree-translate
IREE_BENCH=iree-benchmark-module
MLIRLUS=../../../mlir-lus/mlirlus
PY=python

# Compiler setup
CC=clang -O3
LD=clang++
