#-------------------------------------------------------------
# Configuration -- set up accordingly
#-------------------------------------------------------------

# IREE_DIR=/local/hpompoug/github/iree
IREE_DIR=/home/hpompougnac/src/projects/mlir-lus/iree
IREE_BUILD_DIR=/home/hpompougnac/bin/iree-build
# IREE_BUILD_DIR=/local/hpompoug/bin/iree-build
TF_OPT=tf-opt
IREE_OPT=iree-opt
IREE_TRANSLATE=iree-translate
IREE_BENCH=iree-benchmark-module
MLIRLUS=../../../src/mlirlus
PY=python

# Compiler setup
CC=clang -O3
LD=clang++
